--- 
 - name: Verify if Zabbix Agent Exists
   stat: path=/usr/sbin/zabbix_agentd
   register: zbx_agent

 - name: RHEL: Install Zabbix Repo
   package: name="http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm" state=present
   become: yes
   when: ansible_os_family == 'Redhat'

 - name: Apt: Configure Zabbix Repo
   template: src=zabbix.apt.j2 dest=/etc/apt/sources.list.d/zabbix.list
   when: ansible_os_family == 'Debian'
   become: yes

 - name: Create additional conf dir
   file: path=/etc/zabbix/zabbix_agentd.conf.d state=directory owner=zabbix
   become: yes

 - name: Install Zabbix Packages
   package: name={{ item }} state=present
   with_items:
    - zabbix-agent
    - zabbix-sender
   become: yes

 - name: Configure Zabbix Agent
   template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
   become: yes

 - name: Verify Service State
   service: name={{ item }} state=restarted enabled=True
   with_items:
    - zabbix-agent
    - zabbix-sender
